name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@=v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn (in act)
        if: ${{ env.ACT }}
        run: npm -g install yarn
      - name: Install Dependencies if Cache Miss
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn --immutable
      - name: Run ESLint
        run: yarn lint --fix=false

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn (in act)
        if: ${{ env.ACT }}
        run: npm -g install yarn
      - name: Install Dependencies if Cache Miss
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn --immutable
      - name: Compile Projects
        run: yarn build

  Testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn (in act)
        if: ${{ env.ACT }}
        run: npm -g install yarn
      - name: Install Dependencies if Cache Miss
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn --immutable
      - name: Build Packages
        run: yarn build
      - name: Run tests
        run: yarn test
